### ISSUE TITLE
Failed to build from sources

### ISSUE THREAD

**Issue by hutorny** [remakeelectric/owrt_pub_feeds#8]
`In file included from mosquitto.c:33:0:
./mosquitto_internal.h:40:20: fatal error: ares.h: No such file or directory
 #  include <ares.h>
`
Workaround described on [ibm.com](https://www.ibm.com/developerworks/community/blogs/df2c0f19-cc05-4675-a730-b5ba9eef7f0a/entry/How_to_resolve_ares_h_No_such_file_when_building_Mosquito?lang=ru)
'WITH_SRV:=no'
does not help
Workaround described on  [building-mosquitto](http://goochgooch.co.uk/2014/08/01/building-mosquitto-1-4/) does not deal with cross-compiling.

**Comment by karlp** [comment]
c-ares is maintained in openwrt packages.  if you did 

```
./scripts/feeds install -p owrt_pub_feeds mosquitto
```

It should have pulled in c-ares already.  What branch of openwrt/lede are you working on?  And does your regular build environment work as you expect?

**Comment by karlp** [comment]
(The advice on goochgooch.co.uk about blindly sudo installing fixed versions of various dependencies is _terrible_ advice)

**Comment by hutorny** [comment]
I did as build instruction advises:
`./scripts/feeds install -p owrt_pub_feeds -a`

Now `./scripts/feeds install -p owrt_pub_feeds mosquitto` does nothing

**Comment by karlp** [comment]
and the other questions?  What branch are you working on?  mosquitto actually exists in upstream core packages back to AA.  you only need this repository if you want newer versions of mosquitto.  In those cases, you need to uninstall mosquitto and reinstall mosquitto using the -p flag to ensure you get mosquitto from this feed.  You're currently not including enough information for me to work with.  The issue is clearly the c-ares dependency.  you can poke at scripts/feeds install/uninstall and the -p flag, and you can use menuconfig to check that c-ares is available and selected.  There's no support for WITH_SRV being disabled in the package.

**Comment by shawnchain** [comment]
same issue here, with official 15.05.1 SDK and BUILDER to customize my image but no luck.

**Comment by karlp** [comment]
then open a new issue, and answer the same questions.  And note well that this is even _less_ relevant for 15.05 which already includes 1.4.7 in the binary release, and has 1.4.10 in the packages feed: https://github.com/openwrt/packages/tree/for-15.05/net/mosquitto

(and 1.4.11 has nothing of note for openwrt devices, though I'll eventually update it as well)
